spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 8443
  http2:
    enabled: true