spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

server:
  #  port: 2020
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: c4k
  http2:
    enabled: true